name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source .venv/bin/activate
        # Add your test command here, for example:
        # pytest tests/

    - name: Build with PyInstaller
      run: |
        source .venv/bin/activate
        pip install pyinstaller
        pyinstaller system_monitor.spec

    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: system-monitor-build
        path: dist/
